import type { RunDetail, Scenario } from '../lib/contracts';
import { expectedRule } from '../lib/evidence-presentation';
import { ScenarioEvidence } from './evidence';
import { AssertionBadge, Badge, JsonDetails } from './shared';

export function Finding({ scenario, detail, onRepair, busy }: { scenario: Scenario; detail: RunDetail; onRepair: () => void; busy: boolean }) {
  const apiFailed = scenario.api.verdict === 'fail';
  const browserFailed = scenario.browser.verdict === 'fail';
  const stateFailed = scenario.state.verdict === 'fail';
  const title = scenario.api.code === 'PROTECTED_DATA_LEAK' ? 'Protected data was returned when access should be denied.' : scenario.api.code === 'PAID_ACCESS_DENIED' ? 'A confirmed paying user was denied protected access.' : apiFailed ? 'The API response contradicts the approved access policy.' : browserFailed ? 'The browser result contradicts the approved policy.' : stateFailed ? 'Stored application state differs from provider state.' : 'Recorded scenario evidence';
  return <article className="finding"><div className="finding-topline"><code>{scenario.id}</code><Badge tone={apiFailed ? 'red' : browserFailed || stateFailed ? 'amber' : 'neutral'}>{apiFailed ? 'High · Access mismatch' : stateFailed ? 'Medium · State drift' : browserFailed ? 'Medium · UI mismatch' : 'Evidence inspection'}</Badge></div><h3>{title}</h3><div className="finding-grid"><div><h4>Approved expected rule</h4><p>{expectedRule(scenario.id)}</p><p>This is the saved rule for the scenario. The worker's recorded assertions determine the result; this view does not evaluate access again.</p></div><div><h4>Recorded assertions</h4><dl className="finding-assertions"><div><dt>API</dt><dd><AssertionBadge assertion={scenario.api} /><code>{scenario.api.code}</code></dd></div><div><dt>Browser</dt><dd><AssertionBadge assertion={scenario.browser} /><code>{scenario.browser.code}</code></dd></div><div><dt>Stored state</dt><dd><AssertionBadge assertion={scenario.state} /><code>{scenario.state.code}</code></dd></div></dl></div></div><h4>What the sources recorded</h4><ScenarioEvidence detail={detail} scenario={scenario} /><Reproduction detail={detail} scenario={scenario} /><div className="finding-limit"><strong>What remains uncertain</strong><p>No source-code cause is established by these observations alone. A suspected cause is not verified until a repair passes the unchanged reproduction and required regression checks. {detail.run.mode === 'local_replay' ? 'This run used local replay and does not verify real Stripe webhook delivery.' : 'Review synchronization, evidence freshness, and coverage limits in the report.'}</p></div>{(apiFailed || browserFailed || stateFailed) && <button className="button secondary" disabled={busy} onClick={onRepair}>Prepare repair <span aria-hidden="true">↗</span></button>}</article>;
}

export function Reproduction({ detail, scenario }: { detail: RunDetail; scenario: Scenario }) {
  const { run } = detail;
  return <section className="reproduction"><h4>Reproduction and provenance</h4><ol><li>Use target build <code>{run.targetBuild}</code> with immutable policy <code>{run.policy.hash}</code>.</li><li>Create fresh, run-owned fixtures and obtain an ordinary session. Do not reuse a canceled subscription or a mutated test clock.</li><li>Execute the approved lifecycle through <strong>{scenario.id}</strong> in <strong>{run.mode}</strong> mode, for price <code>{run.policy.priceId}</code>.</li><li>Wait up to the approved {run.policy.syncWindowSeconds} real seconds for synchronization, then collect provider, application, API, and browser observations together. Request <code>GET /api/export</code> and use the dashboard's real export action.</li><li>Apply the unchanged worker predicates and retain the exact fixture marker check. Do not treat an HTTP 200 or a plan label alone as a pass.</li></ol><JsonDetails title={`${scenario.observationIds.length} linked evidence references and reproduction binding`} value={{ runId: run.id, scenarioId: scenario.id, mode: run.mode, targetBuild: run.targetBuild, policyHash: run.policy.hash, featureConfigHash: run.featureConfigHash, ...(run.projectConfigHash ? { projectConfigHash: run.projectConfigHash } : {}), observationIds: scenario.observationIds }} /></section>;
}
