import type { RunDetail } from '../lib/contracts';
import { expectedRule } from '../lib/evidence-presentation';
import { ScenarioEvidence } from './evidence';
import { Reproduction } from './findings';
import { AssertionBadge, EmptyState, JsonDetails, ModeBadge, ReplayNotice, RunBadge } from './shared';

export function RunReport({ detail }: { detail: RunDetail }) {
  const { run } = detail;
  const assertions = detail.scenarios.flatMap(scenario => [scenario.api, scenario.browser, scenario.state]);
  const counts = ['pass', 'fail', 'inconclusive', 'unsupported', 'skipped'].map(verdict => ({ verdict, count: assertions.filter(assertion => assertion.verdict === verdict).length }));
  return <section className="panel"><div className="panel-heading"><div><h2>Run report</h2><p>Expected rules, recorded behavior, and the limits of this verification.</p></div><div className="report-downloads"><a className="button secondary small" href={`/api/runs/${encodeURIComponent(run.id)}/report?format=markdown`} download>Markdown ↓</a><a className="button secondary small" href={`/api/runs/${encodeURIComponent(run.id)}/report?format=json`} download>JSON ↓</a></div></div><div className="panel-inset">{run.mode === 'local_replay' && <ReplayNotice />}<div className="report-identity"><RunBadge run={run} /><ModeBadge mode={run.mode} /><span>{detail.scenarios.length} of 4 scenarios recorded · {assertions.length} of 12 assertions recorded</span></div><div className="report-counts">{counts.map(item => <span key={item.verdict}><strong>{item.count}</strong> {item.verdict}</span>)}</div><p className="report-disclaimer">Missing, skipped, unsupported, and inconclusive checks do not pass. This report covers the recorded target build and policy, not every billing or security condition.</p><dl className="report-binding"><div><dt>Run</dt><dd><code>{run.id}</code></dd></div><div><dt>Target build</dt><dd><code>{run.targetBuild}</code></dd></div><div><dt>Policy hash</dt><dd><code>{run.policy.hash}</code></dd></div><div><dt>Feature binding</dt><dd><code>{run.featureConfigHash}</code></dd></div></dl>{detail.scenarios.length ? detail.scenarios.map(scenario => <details className="report-scenario" key={scenario.id}><summary><strong>{scenario.id}</strong><span>API <AssertionBadge assertion={scenario.api} /></span><span>Browser <AssertionBadge assertion={scenario.browser} /></span><span>State <AssertionBadge assertion={scenario.state} /></span></summary><div><h4>Approved expected rule</h4><p>{expectedRule(scenario.id)}</p><ScenarioEvidence detail={detail} scenario={scenario} /><Reproduction detail={detail} scenario={scenario} /></div></details>) : <EmptyState title="No scenario observations yet">The saved policy expresses the expected behavior. No executed result has been recorded for this run.</EmptyState>}<JsonDetails title="Immutable policy" value={run.policy} /><JsonDetails title="Cleanup receipts and unresolved fixtures" value={detail.cleanup} /><JsonDetails title="Repair receipts" value={detail.repairs} /><div className="coverage-note"><div><strong>Coverage and limitations</strong>{detail.coverageLimits.length ? detail.coverageLimits.map((limit, index) => <p key={index}>{limit}</p>) : <p>No additional coverage statements were returned. This absence does not expand the approved test scope.</p>}</div></div></div></section>;
}
